# This file is a template, and might need editing before it works on your project.
name: publish

on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: node:latest
    
    steps:
    - uses: actions/checkout@v1
